---
HELM_REPO_NAME: grafana
HELM_REPO_URL: https://grafana.github.io/helm-charts
HELM_CHART_NAME: loki
HELM_RELEASE_NAME: monitoring-loki

HELM_PROMTAIL_CHART_NAME: promtail
HELM_PROMTAIL_RELEASE_NAME: monitoring-promtail

image_loki_repository: "grafana/loki"
image_loki_tag: "2.2.0"
image_loki_pullPolicy: IfNotPresent

image_promtail_repository: "grafana/promtail"
image_promtail_tag: "latest"
image_promtail_pullPolicy: IfNotPresent
