#
# GITLAB CI Variables:
# --------------------
#
# File: DEPLOY_KEY_PRIVATE_PROD: private ssh key
# File: DEPLOY_KEY_PUBLIC_PROD: public ssh key
# File: INVENTORY_PROD: ansible inventory file
#
# Variable: TARGET_HOST_PROD: IP address of target host
# Variable: TARGET_HOSTNAME_PROD: name of target host from inventory (e.g. demo)
#

stages:
#    - verify
    - staging
    - prod
    - test

image: willhallonline/ansible:2.10-ubuntu-20.04

variables: &global-variables
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'
    ANSIBLE_CONFIG: "ansible.cfg"
    ANSIBLE_SCP_IF_SSH: 'y'
    DEBIAN_FRONTEND: 'noninteractive'


####################################
######    GENERAL SCRIPTS   ########
####################################

.pre_deploy: &pre_deploy
    - apt-get update -y && apt-get install curl apt-transport-https -y
    # Add Helm package repo
    - curl https://baltocdn.com/helm/signing.asc | apt-key add -
    - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
    # Add kubectl package repo
    - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
    # Install required system packages
    - apt-get update -y && apt install openssh-client curl vim git less iputils-ping sshpass libpq-dev gcc python3-dev musl-dev helm kubectl -y
    # Install required python packages
    - python3 -m pip install jmespath docker psycopg2-binary pymongo
    - ansible-galaxy install -r requirements.yml



####################################
######     VERIFY / LINT    ########
####################################


### verify syntaxs etc...
#verify_commit:
#  stage: verify
#  environment:
#    name: "Verify ansible playbooks"
#  script:
#    # Install required python packages
#    - python3 -m pip install 'openshift==0.11' jmespath docker psycopg2-binary pymongo
#    - ansible-galaxy collection install community.kubernetes
#    - ansible-galaxy install -r requirements.yml
#    - 'which ansible-lint || ( pip install ansible-lint )'
#    - ansible-lint -x experimental -v 02_setup_k8s/setup_k8s_playbook_01.yml
#    - ansible-lint -x experimental -v 02_setup_k8s/setup_k8s_playbook_02.yml
#    - ansible-lint -x experimental -v 02_setup_k8s/setup_k8s_playbook_03.yml
#    - ansible-lint -x experimental -v 03_setup_k8s_platform/full_install.yml


####################################
######     STAGING       ###########
####################################


.ssh_config_staging: &ssh_config_staging
    # Get SSH keys
    - mkdir -p /root/.ssh
    - mv "$STAGING_KEY_PRIVATE" /root/.ssh/id_rsa_sc_admin
    - mv "$STAGING_KEY_PUBLIC" /root/.ssh/id_rsa_sc_admin.pub
    # Add SSH Key
    - chmod 600 /root/.ssh/id_rsa_sc_admin
    - chmod 600 /root/.ssh/id_rsa_sc_admin.pub
    - eval "$(ssh-agent -s)"
    - ssh-add /root/.ssh/id_rsa_sc_admin
    - ssh-keyscan -H $STAGING_TARGET_HOST >> /root/.ssh/known_hosts
    # Add SSH Config for acn user
    - touch /root/.ssh/config
    - echo "Host $STAGING_TARGET_HOST" >> /root/.ssh/config
    - echo "    HostName $STAGING_TARGET_HOST" >> /root/.ssh/config
    - echo "    User acn" >> /root/.ssh/config
    - echo "    PreferredAuthentications publickey,password" >> /root/.ssh/config
    - echo "    IdentityFile /root/.ssh/id_rsa_sc_admin" >> /root/.ssh/config
    - chmod 600 /root/.ssh/config


# deploy for staging
deploy_staging_k8s:
  script:
    - *pre_deploy
    - python3 -m pip install 'openshift==0.11'
    # Start installing k8s
    - mv "$STAGING_INVENTORY_FULL" inventory
    - *ssh_config_staging
    - ansible-playbook -i inventory -l $TARGET_HOSTNAME -u root 02_setup_k8s/setup_k8s_playbook_01.yml
    - ansible-playbook -i inventory -l $TARGET_HOSTNAME -u acn 02_setup_k8s/setup_k8s_playbook_02.yml
    - ansible-playbook -i inventory -l localhost -u acn 02_setup_k8s/setup_k8s_playbook_03.yml
  when: manual
  stage: staging
  environment:
    name: "Deploy Staging Kubernetes"
  artifacts:
    paths:
      - .facts/
    expire_in: never
    when: on_success

.prepare_deploy_staging: &prepare_deploy_staging
    - *pre_deploy
    - python3 -m pip install 'openshift==0.12.1'
    - mv "$STAGING_INVENTORY_FULL" inventory
    - *ssh_config_staging
    # Get kubeconfig from kubernetes
    - mkdir -p /root/.kube
    - scp acn@$STAGING_TARGET_HOST:/home/acn/.kube/kubeconfig_txl_staging /root/.kube/kubeconfig_txl_staging
    - head -1 /root/.kube/kubeconfig_txl_staging
    - ansible-galaxy collection install community.kubernetes

deploy_staging_platform:
  script:
    - *prepare_deploy_staging
    - ansible-playbook -i inventory -l localhost 03_setup_k8s_platform/full_install.yml
  when: manual
  stage: staging
  environment:
    name: "Deploy Staging Platform"
  artifacts:
    paths:
      - .facts/
    expire_in: never
    when: on_success

deploy_staging_ckan:
  script:
    - *prepare_deploy_staging
    - ansible-playbook -i inventory -l localhost 03_setup_k8s_platform/deploy_ckan_playbook.yml
  when: manual
  stage: staging
  environment:
    name: "Deploy Staging CKAN"
  artifacts:
    paths:
      - .facts/
    expire_in: never
    when: on_success


####################################
######     PRODUCTION    ###########
####################################

.ssh_config_prod: &ssh_config_prod
    # Get SSH keys
    - mkdir -p /root/.ssh
    - mv "$PROD_KEY_PRIVATE" /root/.ssh/id_rsa_sc_admin
    - mv "$PROD_KEY_PUBLIC" /root/.ssh/id_rsa_sc_admin.pub
    # Add SSH Key
    - chmod 600 /root/.ssh/id_rsa_sc_admin
    - chmod 600 /root/.ssh/id_rsa_sc_admin.pub
    - eval "$(ssh-agent -s)"
    - ssh-add /root/.ssh/id_rsa_sc_admin
    - ssh-keyscan -H $PROD_TARGET_HOST >> /root/.ssh/known_hosts
    # Add SSH Config for acn user
    - touch /root/.ssh/config
    - echo "Host $PROD_TARGET_HOST" >> /root/.ssh/config
    - echo "    HostName $PROD_TARGET_HOST" >> /root/.ssh/config
    - echo "    User acn" >> /root/.ssh/config
    - echo "    PreferredAuthentications publickey,password" >> /root/.ssh/config
    - echo "    IdentityFile /root/.ssh/id_rsa_sc_admin" >> /root/.ssh/config
    - chmod 600 /root/.ssh/config

# deploy for prod
deploy_prod_k8s:
  script:
    - *pre_deploy
    - python3 -m pip install 'openshift==0.11'
    # Start installing k8s
    - mv "$PROD_INVENTORY_FULL" inventory
    - *ssh_config_prod
    - ansible-playbook -i inventory -l $TARGET_HOSTNAME -u root 02_setup_k8s/setup_k8s_playbook_01.yml
    - ansible-playbook -i inventory -l $TARGET_HOSTNAME -u acn 02_setup_k8s/setup_k8s_playbook_02.yml
    - ansible-playbook -i inventory -l localhost -u acn 02_setup_k8s/setup_k8s_playbook_03.yml
  when: manual
  stage: prod
  environment:
    name: "Deploy Production Kubernetes"
  artifacts:
    paths:
      - .facts/
    expire_in: never
    when: on_success

.prepare_deploy_prod: &prepare_deploy_prod
    - *pre_deploy
    - python3 -m pip install 'openshift==0.12.1'
    - mv "$PROD_INVENTORY_FULL" inventory
    - *ssh_config_prod
    # Get kubeconfig from kubernetes
    - mkdir -p /root/.kube
    - scp acn@$PROD_TARGET_HOST:/home/acn/.kube/kubeconfig_txl_prod /root/.kube/kubeconfig_txl_prod
    - head -1 /root/.kube/kubeconfig_txl_prod
    - ansible-galaxy collection install community.kubernetes

deploy_production_platform:
  script:
    - *prepare_deploy_prod
    - ansible-playbook -i inventory -l localhost 03_setup_k8s_platform/full_install.yml
  when: manual
  stage: prod
  environment:
    name: "Deploy Production Platform"
  artifacts:
    paths:
      - .facts/
    expire_in: never
    when: on_success

deploy_prod_ckan:
  script:
    - *prepare_deploy_prod
    - ansible-playbook -i inventory -l localhost 03_setup_k8s_platform/deploy_ckan_playbook.yml
  when: manual
  stage: prod
  environment:
    name: "Deploy Production CKAN"
  artifacts:
    paths:
      - .facts/
    expire_in: never
    when: on_success