apiVersion: v2
name: webgis-qgisserver
version: 0.1.0
description: A Helm chart to deploy QGIS Server (https://www.qgis.org/) for the FUTR-HUB WebGIS Protoype
type: application
keywords:
  - futr-hub
  - webgis
  - qgisserver
home: https://gitlab.com/berlintxl/futr-hub/
sources:
  - https://gitlab.com/berlintxl/futr-hub/platform/data-platform-k8s/-/tree/master/03_setup_k8s_platform/files/helmcharts/webgis-qgisserver/
maintainers:
  - name: Olaf Heinemann
    email: olaf.heinemann@omp.de
appVersion: "3.16.0"
