repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    # -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.3.7
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
- repo: https://github.com/mattlqx/pre-commit-ruby
  rev: v1.3.3
  hooks:
  # - id: rubocop
  # - id: foodcritic
  - id: cookstyle
  # - id: rspec
  - id: chef-cookbook-version
