---
# file: 02_setup_k8s/setup_k8s_playbook_03.yml

- hosts: localhost
  become: false
  gather_facts: false

  collections:
    - kubernetes.core

  vars_files:
    - vars/default.yml

  environment: "{{ proxy_env }}"

  tasks:
    - import_tasks: tasks/05_cert_manager.yml
