---
# file: 02_setup_k8s/setup_k8s_playbook_02.yml
- hosts: k8s_cluster
  become: true
  gather_facts: false

  tasks:
    - name: Read default values
      ansible.builtin.include_vars:
        file: default.yml

    - import_tasks: tasks/02_prepare_system.yml

    - import_tasks: tasks/03_install_microk8s.yml

    - import_tasks: tasks/04_save_kubeconfig.yml
