---

####################################
#### LOG IN IDENTITY PROVIDER   ####
####################################


- name: Login into APIM management API using IDM provider
  uri:
    method: POST
    url: "https://idm.{{ DOMAIN }}/auth/realms/platform-central/protocol/openid-connect/token"
    return_content: yes
    body_format: form-urlencoded
    body:
    - [ grant_type, "password" ]
    - [ username, "admin@{{ DOMAIN }}" ]
    - [ password, "{{ SC_ADMIN_PASSWORD }}" ]
    - [ client_id, "platform-central-main" ]
    - [ client_secret, "{{ IDM_CLIENT_SECRET }}" ]
    headers:
      Accept: application/json
    status_code: 200
  register: user


- name: Exchange token at APIM
  uri:
    method: POST
    url: "https://api.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/auth/oauth2/keycloak/exchange?token={{ user.json.access_token }}"
    return_content: yes
    headers:
      Accept: application/json
    status_code: 200
  register: new_token


- name: Get IDM user id
  uri:
    method: GET
    url: "https://api.{{ DOMAIN }}/management/organizations/DEFAULT/user"
    return_content: yes
    headers:
      Accept: application/json
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 200
  register: idm_user_id


######################################
### Create MIN.IO Server API Entry ###
######################################

- name: Create S3 API Entry
  uri:
    method: POST
    url: "https://api.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/apis/import"
    return_content: yes
    body_format: json
    body: |
      {
        "proxy": {
          "endpoints": [
            {
              "name":"default",
              "target":"{{ s3_api_endpoint }}",
              "inherit":true
            }
          ],
          "context_path":"{{ s3_api_publicPath }}"
        },
        "pages":[],
        "plans":[],
        "tags":[],
        "name":"S3 API for Object Database",
        "version":"1.0",
        "description":"S3 compatible Access"
      }
    headers:
      Accept: application/json
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 200,400
  register: s3API

- debug:
    msg: "Failed. S3 API already existing?"
  when: s3API.status == 400

- name: Update to final Values
  uri:
    method: PUT
    url: "https://api.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/apis/{{ s3API.json.id }}"
    return_content: yes
    body_format: json
    body: "{{ lookup('template', 'gravitee/s3_server.json.j2') }}"
    headers:
      Accept: application/json
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 200
  when: s3API.status != 400

- name: Create Subscription Plan based on API Keys
  uri:
    method: POST
    url: "https://api.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/apis/{{ s3API.json.id }}/plans"
    return_content: yes
    body_format: json
    body: "{{ lookup('template', 'gravitee/create_plan_key_less.json.j2') }}"
    headers:
      Accept: application/json
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 201
  when: s3API.status != 400

- name: Start the API
  uri:
    method: POST
    url: "https://api.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/apis/{{ s3API.json.id }}?action=START"
    return_content: yes
    headers:
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 204
  when: s3API.status != 400
