---
- name: Log into registry and reauthorize
  community.general.docker_login:
    registry_url: registry.gitlab.com
    username: "{{ REGISTRY_ACCESS_USER }}"
    password: "{{ REGISTRY_ACCESS_TOKEN }}"
    reauthorize: yes

- name: Deploy webscraper service
  docker_container:
    name: 03_webscraper
    image: "{{ WEBSCRAPER_REGISTRY }}"
    restart_policy: always
    networks:
      - name: "public"
    networks_cli_compatible: yes
    purge_networks: yes
    network_mode: "public"
    state: started
    labels:
      com.docker.compose.project: "usecases"
      traefik.enable: "true"
      traefik.docker.network: "public"

- name: Ensure remote temp directory exists
  file:
    path: /opt/scp/ansible/grafana/monitoring/provisioning/dashboards/temp/
    recurse: yes
    state: directory
    mode: '0755'

- name: Create webscraper dashboard from template
  template:
    src: grafana/dashboards/03_webscraper_dashboard.json.j2
    dest: /opt/scp/ansible/grafana/monitoring/provisioning/dashboards/temp/03_webscraper_dashboard.json
    mode: '0666'

- name: (Re-)Import Grafana Dashboard
  community.grafana.grafana_dashboard:
        grafana_url: https://grafana.{{ DOMAIN }}
        url_username: admin
        url_password: "{{ GRAFANA_ADMIN_PASSWORD }}"
        state: present
        commit_message: Updated by ansible
        overwrite: yes
        path: /opt/scp/ansible/grafana/monitoring/provisioning/dashboards/temp/03_webscraper_dashboard.json
