{{- $tier := "server" -}}
{{- $fullName := include "webgis-qgisserver.fullname" (merge (dict "tier" $tier) .) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "webgis-qgisserver.chart" . }}
    app: {{ include "webgis-qgisserver.name" . }}
    component: {{ $tier }}
spec:
  selector:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "webgis-qgisserver.chart" . }}
    app: {{ include "webgis-qgisserver.name" . }}
    component: {{ $tier }}
  type: ClusterIP
  ports:
    - port: {{ .Values.qgis.server.ports.servicePort }}
      targetPort: {{ .Values.qgis.server.ports.targetPort }}
