{{- $fullName := include "webgis-qgisserver.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "webgis-qgisserver.labels" . | nindent 4 }}
type: Opaque
data:
  postgis_user: {{ .Values.qgis.postgis_user | b64enc | quote }}
  postgis_password: {{ .Values.qgis.postgis_user_password | b64enc | quote }}
stringData:
  pg_service.conf: |
    [{{ .Values.qgis.postgis_service }}]
    host={{ .Values.qgis.postgis_host }}
    port={{ .Values.qgis.postgis_port }}
    dbname={{ .Values.qgis.postgis_dbname }}
    user={{ .Values.qgis.postgis_user }}
    password={{ .Values.qgis.postgis_user_password }}
    sslmode={{ .Values.qgis.postgis_sslmode }}
