apiVersion: v1
data:
  POSTGRES_DATABASE: '{{ KEYCLOAK_POSTGRES_DATABASE }}'
  POSTGRES_EXTERNAL_ADDRESS: '{{ KEYCLOAK_POSTGRES_EXTERNAL_ADDRESS }}'
  POSTGRES_EXTERNAL_PORT: NTQzMg==  # 5432
  # POSTGRES_EXTERNAL_PORT: MzEzNTI=  # 31352
  POSTGRES_HOST: '{{ KEYCLOAK_POSTGRES_HOST }}'
  POSTGRES_PASSWORD: '{{ KEYCLOAK_POSTGRES_PASSWORD }}'
  POSTGRES_SUPERUSER: dHJ1ZQ==
  POSTGRES_USERNAME: '{{ KEYCLOAK_POSTGRES_USERNAME }}'
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque

---

apiVersion: v1
data:
  MASTER_USERNAME: '{{ keycloak.realm_master_username | b64encode}}'
  MASTER_PASSWORD: '{{ keycloak.realm_master_password | b64encode}}'
kind: Secret
metadata:
  name: '{{ IDM_ADMIN_K8S_SECRET_NAME }}'
type: Opaque
