apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: "{{ k8s_namespace }}"
  annotations:
    kubernetes.io/ingress.class: "{{ default.K8S_INGRESS_CLASS }}"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-buffer-size: 10k
    nginx.ingress.kubernetes.io/server-snippet: |2-

                            location ~* "^/auth/realms/master/metrics" {
                                return 301 /auth/realms/master;
                              }
spec:
  tls:
  - hosts:
    - "{{ keycloak.ingress_tls_host }}"
    secretName: "{{ keycloak.ingress_secert_name }}"
  rules:
  - host: "{{ keycloak.ingress_rules_host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8443

