---
# file: 03_setup_k8s_platform/configure_prerequisites.yml

- name: Setup full_install prerequisites
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Add Jetstack Repo
    community.kubernetes.helm_repository:
      repo_name: jetstack
      repo_url: "https://charts.jetstack.io"