---
# file: 03_setup_k8s_platform/deploy_webgis_postgis_playbook.yml
- name: Deploy PostGIS for WebGIS
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read default values
      ansible.builtin.include_vars:
        file: default.yml
        name: default

    - name: Read PostGIS values
      ansible.builtin.include_vars:
        file: webgis_postgis.yml
        name: postgis

    - name: Set default facts for K8S
      ansible.builtin.set_fact:
        k8s_config: "{{ default.K8S_KUBECONFIG }}"
        k8s_context: "{{ default.K8S_CONTEXT }}"
        k8s_namespace: "{{ default.K8S_NAMESPACE_GEODATA }}"

    - name: Set facts for ChartMuseum
      ansible.builtin.set_fact:
        cm_port: "{{ default.CM_PORT }}"
        cm_storage: "{{ default.CM_STORAGE }}"
        cm_storage_local_rootdir: "{{ default.CM_STORAGE_LOCAL_ROOTDIR }}"
        cm_context_path: "{{ default.CM_CONTEXT_PATH }}"
        helm_repo_url: "{{ default.HELM_REPO_URL }}"
        helm_repo_name: "{{ default.HELM_REPO_NAME }}"

    - name: Set facts for PostGIS Helm chart
      ansible.builtin.set_fact:
        postgis_helm_chart_name: "{{ postgis.HELM_CHART_NAME }}"
        postgis_helm_release_name: "{{ postgis.HELM_RELEASE_NAME }}"

    - name: Install Helm package with values loaded from template
      community.kubernetes.helm:
        name: "{{ postgis_helm_release_name }}"
        # chart_ref: "{{ helm_repo_name }}/{{ postgis_helm_chart_name }}"
        chart_ref: "files/helmcharts/{{ postgis_helm_chart_name }}"
        kubeconfig: "{{ k8s_config }}"
        context: "{{ k8s_context }}"
        release_namespace: "{{ k8s_namespace }}"
        update_repo_cache: true
        create_namespace: true
        values: "{{ lookup('template', 'templates/webgis/postgis_values.yaml.j2') | from_yaml }}"


