---
# file: 03_setup_k8s_platform/deploy_ckan_playbook.yml
- name: Deploy CKAN
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read default values
      ansible.builtin.include_vars:
        file: default.yml
        name: default

    - name: Read CKAN values
      ansible.builtin.include_vars:
        file: ckan_ckan.yml
        name: ckan

    - name: Set default facts for K8S
      ansible.builtin.set_fact:
        k8s_config: "{{ default.K8S_KUBECONFIG }}"
        k8s_context: "{{ default.K8S_CONTEXT }}"
        k8s_namespace: "{{ default.K8S_NAMESPACE_CKAN }}"

    - name: Set facts for ChartMuseum
      ansible.builtin.set_fact:
        cm_port: "{{ default.CM_PORT }}"
        cm_storage: "{{ default.CM_STORAGE }}"
        cm_storage_local_rootdir: "{{ default.CM_STORAGE_LOCAL_ROOTDIR }}"
        cm_context_path: "{{ default.CM_CONTEXT_PATH }}"
        helm_repo_url: "{{ default.HELM_REPO_URL }}"
        helm_repo_name: "{{ default.HELM_REPO_NAME }}"

    - name: Set facts for CKAN Helm chart
      ansible.builtin.set_fact:
        ckan_helm_repo_name: "{{ ckan.HELM_REPO_NAME }}"
        ckan_helm_repo_url: "{{ ckan.HELM_REPO_URL }}"
        ckan_helm_chart_name: "{{ ckan.HELM_CHART_NAME }}"
        ckan_helm_release_name: "{{ ckan.HELM_RELEASE_NAME }}"

    - name: Add CKAN Helm repo
      community.kubernetes.helm_repository:
        name: "{{ ckan_helm_repo_name }}"
        url: "{{ ckan_helm_repo_url }}"

    - name: Install Helm package with values loaded from template
      community.kubernetes.helm:
        name: "{{ ckan_helm_release_name }}"
        chart_ref: "{{ ckan_helm_repo_name }}/{{ ckan_helm_chart_name }}"
        kubeconfig: "{{ k8s_config }}"
        context: "{{ k8s_context }}"
        release_namespace: "{{ k8s_namespace }}"
        update_repo_cache: true
        create_namespace: true
        values: "{{ lookup('template', 'templates/ckan/ckan_values.yaml.j2') | from_yaml }}"
