---
# file: 03_setup_k8s_platform/deploy_webgis_pgadmin_playbook.yml
- name: Deploy pgAdmin for WebGIS
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/default.yml

  tasks:
    - name: Read default values
      ansible.builtin.include_vars:
        file: default.yml
        name: default

    - name: Read pgAdmin values
      ansible.builtin.include_vars:
        file: webgis_pgadmin.yml
        name: pgadmin

    - name: Set default facts for K8S
      ansible.builtin.set_fact:
        k8s_config: "{{ default.K8S_KUBECONFIG }}"
        k8s_context: "{{ default.K8S_CONTEXT }}"
        k8s_namespace: "{{ default.K8S_NAMESPACE_GEODATA }}"

    # - name: Set facts for ChartMuseum
    #   ansible.builtin.set_fact:
    #     cm_port: "{{ default.CM_PORT }}"
    #     cm_storage: "{{ default.CM_STORAGE }}"
    #     cm_storage_local_rootdir: "{{ default.CM_STORAGE_LOCAL_ROOTDIR }}"
    #     cm_context_path: "{{ default.CM_CONTEXT_PATH }}"
    #     helm_repo_url: "{{ default.HELM_REPO_URL }}"
    #     helm_repo_name: "{{ default.HELM_REPO_NAME }}"

    - name: Set facts for pgAdmin Helm chart
      ansible.builtin.set_fact:
        pgadmin_helm_repo_name: "{{ pgadmin.HELM_REPO_NAME }}"
        pgadmin_helm_repo_url: "{{ pgadmin.HELM_REPO_URL }}"
        pgadmin_helm_chart_name: "{{ pgadmin.HELM_CHART_NAME }}"
        pgadmin_helm_release_name: "{{ pgadmin.HELM_RELEASE_NAME }}"

    - name: Add pgAdmin Helm repo
      community.kubernetes.helm_repository:
        name: "{{ pgadmin_helm_repo_name }}"
        url: "{{ pgadmin_helm_repo_url }}"

    - name: Install Helm package with values loaded from template
      community.kubernetes.helm:
        name: "{{ pgadmin_helm_release_name }}"
        chart_ref: "{{ pgadmin_helm_repo_name }}/{{ pgadmin_helm_chart_name }}"
        kubeconfig: "{{ k8s_config }}"
        context: "{{ k8s_context }}"
        release_namespace: "{{ k8s_namespace }}"
        update_repo_cache: true
        create_namespace: true
        values: "{{ lookup('template', 'templates/webgis/pgadmin_values.yaml.j2') | from_yaml }}"
