---
- name: Deploy Postgres Operator
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/default.yml

  tasks:
    - name: Read default values
      ansible.builtin.include_vars:
        file: default.yml
        name: default

    - name: Read POSTGRES values
      ansible.builtin.include_vars:
        file: postgres_operator.yml
        name: postgres

    - name: Set default facts for K8S
      ansible.builtin.set_fact:
        k8s_config: "{{ default.K8S_KUBECONFIG }}"
        k8s_context: "{{ default.K8S_CONTEXT }}"
        k8s_namespace: "{{ default.K8S_NAMESPACE_POSTGRES_OPERATOR }}"

    - name: Set facts for CKAN Helm chart
      ansible.builtin.set_fact:
        postgres_helm_op_chart_url: "{{ postgres.HELM_OP_CHART_URL }}"
        postgres_helm_op_release_name: "{{ postgres.HELM_OP_RELEASE_NAME }}"
        postgres_helm_ui_chart_url: "{{ postgres.HELM_UI_CHART_URL }}"
        postgres_helm_ui_release_name: "{{ postgres.HELM_UI_RELEASE_NAME }}"

    - name: Deploy stable version of postgres operator chart
      community.kubernetes.helm:
        name: "{{ postgres_helm_op_release_name }}"
        chart_ref: "{{ postgres_helm_op_chart_url }}"
        kubeconfig: "{{ k8s_config }}"
        context: "{{ k8s_context }}"
        release_namespace: "{{ k8s_namespace }}"
        update_repo_cache: true
        create_namespace: true
        values: "{{ lookup('template', 'postgres/postgres-op-values.yaml.j2') | from_yaml }}"

    - name: Deploy stable version of postgres operator ui chart
      community.kubernetes.helm:
        name: "{{ postgres_helm_ui_release_name }}"
        chart_ref: "{{ postgres_helm_ui_chart_url }}"
        kubeconfig: "{{ k8s_config }}"
        context: "{{ k8s_context }}"
        release_namespace: "{{ k8s_namespace }}"
        update_repo_cache: true
        create_namespace: true
        values: "{{ lookup('template', 'postgres/postgres-op-ui-values.yaml.j2') | from_yaml }}"

