---
- name: Deploy OAuth2 Proxy
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read default values
      ansible.builtin.include_vars:
        file: default.yml
        name: default

    - name: Read OAuth2 Proxy values
      ansible.builtin.include_vars:
        file: public_oauth2_proxy.yml
        name: oauth2proxy

    - name: Set default facts for K8S
      ansible.builtin.set_fact:
        k8s_config: "{{ default.K8S_KUBECONFIG }}"
        k8s_context: "{{ default.K8S_CONTEXT }}"
        k8s_namespace: "{{ default.K8S_NAMESPACE_PUBLIC }}"

    - name: Set facts for ChartMuseum
      ansible.builtin.set_fact:
        cm_port: "{{ default.CM_PORT }}"
        cm_storage: "{{ default.CM_STORAGE }}"
        cm_storage_local_rootdir: "{{ default.CM_STORAGE_LOCAL_ROOTDIR }}"
        cm_context_path: "{{ default.CM_CONTEXT_PATH }}"
        helm_repo_url: "{{ default.HELM_REPO_URL }}"
        helm_repo_name: "{{ default.HELM_REPO_NAME }}"

    - name: Set facts for OAuth2 Proxy Helm chart
      ansible.builtin.set_fact:
        oauth2proxy_helm_repo_name: "{{ oauth2proxy.HELM_REPO_NAME }}"
        oauth2proxy_helm_repo_url: "{{ oauth2proxy.HELM_REPO_URL }}"
        oauth2proxy_helm_chart_name: "{{ oauth2proxy.HELM_CHART_NAME }}"
        oauth2proxy_helm_release_name: "{{ oauth2proxy.HELM_RELEASE_NAME }}"

    - name: Add OAuth2 Proxy Helm repo
      community.kubernetes.helm_repository:
        name: "{{ oauth2proxy_helm_repo_name }}"
        url: "{{ oauth2proxy_helm_repo_url }}"

    - name: Install Helm package with values loaded from template
      community.kubernetes.helm:
        name: "{{ oauth2proxy_helm_release_name }}"
        chart_ref: "{{ oauth2proxy_helm_repo_name }}/{{ oauth2proxy_helm_chart_name }}"
        kubeconfig: "{{ k8s_config }}"
        context: "{{ k8s_context }}"
        release_namespace: "{{ k8s_namespace }}"
        update_repo_cache: true
        create_namespace: true
        values: "{{ lookup('template', 'templates/public/oauth2-proxy_values.yaml.j2') | from_yaml }}"
