---
# file: 03_setup_k8s_platform/deploy_context_management_stack.yml

- name: Deploy Context Management Stack
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Verify MongoDB credentials are set
      ansible.builtin.fail:
        msg: "ERROR: inventory variable {{ item.key | upper }} is not set."
      when: item.value|length  == 0
      with_items:
       - { key: CMS_MONGO_INITDB_DATABASE, value: "{{ lookup('vars', 'CMS_MONGO_INITDB_DATABASE') }}"}
       - { key: CMS_MONGO_INITDB_ROOT_USERNAME, value: "{{ lookup('vars', 'CMS_MONGO_INITDB_ROOT_USERNAME') }}" }
       - { key: CMS_MONGO_INITDB_ROOT_PASSWORD, value: "{{ lookup('vars', 'CMS_MONGO_INITDB_ROOT_PASSWORD') }}" }
       - { key: CMS_ORION_MONGODB_USER, value: "{{ lookup('vars', 'CMS_ORION_MONGODB_USER') }}" }
       - { key: CMS_ORION_MONGODB_PASSWORD, value: "{{ lookup('vars', 'CMS_ORION_MONGODB_PASSWORD') }}" }
      no_log: true
      tags: always

    - name: Read default values
      ansible.builtin.include_vars:
        file: default.yml
        name: default
      tags: always

    - name: Set default facts for K8S
      ansible.builtin.set_fact:
        k8s_config: "{{ default.K8S_KUBECONFIG }}"
        k8s_context: "{{ default.K8S_CONTEXT }}"
        k8s_namespace: "{{ default.K8S_NAMESPACE_CONTEXT_MANAGEMENT_STACK | lower }}"
      tags: always

    # 1. Create namespace for CM stack
    - name: "Create namespace {{ k8s_namespace }}"
      community.kubernetes.k8s:
        state: present
        kubeconfig: "{{ k8s_config }}"
        context: "{{ k8s_context }}"
        definition:
          api_version: v1
          kind: Namespace
          metadata:
            name: "{{ k8s_namespace }}"
            labels:
              name: "{{ k8s_namespace }}"
      tags: always

    # 2. Install MongoDB
    - name: Install MongoDB
      import_tasks: tasks/context_management-stack/install_mongodb.yml
      tags: mongodb

    # 3. Install Quantum Leap
    - name: Install Quantum Leap
      import_tasks: tasks/context_management-stack/install_quantumleap.yml
      tags: quantumleap

    # 4. Install Orion
    - name: Install Orion
      import_tasks: tasks/context_management-stack/install_orion.yml
      tags: orion

    # 5. Configure Orion API in Gravitee
    - name: Configure Orion API in Gravitee
      import_tasks: tasks/context_management-stack/configure_orion.yml
      tags: config_orion
