- name: Read values to setup and configure keycloak
  ansible.builtin.include_vars:
    file: idm-stack/setup_keycloak.yml
    name: keycloak

- name: Remove the existing Keycloak object via Keycloak Operator
  community.kubernetes.k8s:
    state: absent
    api_version: keycloak.org/v1alpha1
    kind: Keycloak
    name: '{{ keycloak.k8s_name }}'
    namespace: '{{ k8s_namespace }}'
    kubeconfig: '{{ k8s_config }}'
    context: '{{ k8s_context }}'