- name: Read PostgresSQL database values
  ansible.builtin.include_vars:
    file: idm-stack/setup_keycloak_db.yml
    name: postgresql

- name: Get Keycloak Postgres credentials
  community.kubernetes.k8s_info:
    kind: Secret
    namespace: '{{ k8s_namespace }}-db'
    kubeconfig: '{{ k8s_config }}'
    context: "{{ k8s_context }}"
    name: '{{ IDM_DB_ADMIN_SECRET_NAME }}'
  register: keycloak_db_admin

- name: Store Keycloak Postgres Admin Credentials
  set_fact:
    KEYCLOAK_POSTGRES_DATABASE: "{{ common.kc_db_name | b64encode }}"
    KEYCLOAK_POSTGRES_EXTERNAL_ADDRESS: "{{ (( postgresql.cluster_team + '-' + postgresql.cluster_name + '.' + k8s_namespace + '-db.svc.cluster.local' ) | b64encode ) }}"
    KEYCLOAK_POSTGRES_HOST: "{{ (( postgresql.cluster_team + '-' + postgresql.cluster_name + '.' + k8s_namespace + '-db' ) | b64encode ) }}"
    KEYCLOAK_POSTGRES_PASSWORD: "{{ keycloak_db_admin.resources[0].data.password }}"
    KEYCLOAK_POSTGRES_USERNAME: "{{ keycloak_db_admin.resources[0].data.username }}"

- name: Deploy Keycloak secrets
  no_log: true
  community.kubernetes.k8s:
    definition: "{{ item }}"
    namespace: '{{ k8s_namespace }}'
    kubeconfig: '{{ k8s_config }}'
    context: "{{ k8s_context }}"
    state: present
  loop:
    - "{{ lookup('template', 'templates/keycloak/deployment/keycloak-secrets.yaml') | from_yaml_all | list }}"
