- name: Set initial keycloak deployment instances
  set_fact:
    keycloak_replicas: 1

- name: Deploy Keycloak custom resource
  community.kubernetes.k8s:
    definition: "{{ item }}"
    namespace: "{{ k8s_namespace }}"
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
    state: present
  loop:
    - "{{ lookup('template', 'templates/keycloak/deployment/keycloak.yaml') | from_yaml_all | list }}"

- name: Deploy custom Keycloak Ingress
  community.kubernetes.k8s:
    definition: "{{ item }}"
    namespace: "{{ k8s_namespace }}"
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
    state: present
  loop:
    - "{{ lookup('template', 'templates/keycloak/deployment/keycloak-ingress.yaml') | from_yaml }}"

- name: Wait for Keylcoak Start-Up
  wait_for:
    timeout: 240
