services:
  - docker:dind

stages:
  - build

do build:
  tags:
    - shared
  image: docker:stable
  stage: build
  before_script:
    - docker info
    - env
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker build -t webgis-qgisserver .
    - docker tag webgis-qgisserver "$CI_REGISTRY_IMAGE:webgis-qgisserver"
    - docker push "$CI_REGISTRY_IMAGE:webgis-qgisserver"

