---
# file: 01_setup_acn/ansible/fetch_kubeconfig.yml

- name: Fetch KubeConfig from K8S API Server
  hosts: k8s_cluster
  become: yes
  gather_facts: false

  tasks:
    - name: Check if kubeconfig exists in ACN
      ansible.builtin.stat:
        path: "~/.kube/{{ kubeconfig_file }}"
      delegate_to: localhost
      register: result
      become: false

    - name: 'Fail if local {{ kubeconfig_file }} already exists.'
      fail:
        msg: "{{ kubeconfig_file }} already exists locally"
      when: result.stat.exists

    - name: Create local directory /home/acn/.kube in ACN
      ansible.builtin.file:
        path: "/home/acn/.kube"
        state: directory
        owner: acn
        group: acn
        mode: '0755'
      delegate_to: localhost
      when: not result.stat.exists

    - name: Fetch {{ kubeconfig_file }} to ACN
      fetch:
        src: "/home/acn/.kube/{{ kubeconfig_file }}"
        dest: "~/.kube/"
        flat: true
      when: not result.stat.exists

    - name: Change file ownership, group and permissions of kubeconfig
      ansible.builtin.file:
        path: "~/.kube/{{ kubeconfig_file }}"
        owner: acn
        group: acn
        mode: '0600'
      delegate_to: localhost
      become: false
