---
# file: 03_setup_k8s_platform/vars/dataflow-stack/07_switch_lights.yml

# Helm Chart settings --->
HELM_REPO_NAME: stable
# HELM_CHART_NAME: node-red
HELM_CHART_NAME: dataflow-nodered
HELM_RELEASE_NAME: nr-switch-lights

replicaCount: 1
strategyType: Recreate
# -
image_repository: nodered/node-red
image_tag: "1.2.9"
image_pullPolicy: IfNotPresent
# -
nameOverride: ""
fullnameOverride: ""
# -
livenessProbePath: /
readinessProbePath: /
# -
flows: "sc-node-red-flows"
safeMode: "false"
enableProjects: "true"
nodeOptions: ""
extraEnvs: []
timezone: "UTC"
# -
service_type: ClusterIP
service_port: 1888
# -
ingress_enabled: true
ingress_class: public
ingress_tls_acme: true
ingress_host: "nr-switch-lights.{{ DOMAIN }}"
ingress_host_path: "/"
ingress_host_pathType: ImplementationSpecific
ingress_tls_secret: "nr-switch-lights.{{ DOMAIN }}-tls"
# -
persistence_enabled: true
persistence_storageClass: microk8s-hostpath
persistence_accessMode: ReadWriteOnce
persistence_size: 5Gi
persistence_subPath: null
# <--- Helm Chart settings

# Use Case settings --->
NR_SETTINGS: "switch-lights-settings.js"
NR_REPO_TARGET_FOLDER: "sc-node-red-flows"
FLOW_PROJECT: 'gitlab.com/berlintxl/futr-hub/use-cases/switch-lights-on-off/platform-node-red-flows.git'
# <--- Use Case settings
