{{- if not .Values.existingSecret }}
{{- $fullName := include "webgis-postgis.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "webgis-postgis.labels" . | nindent 4 }}
type: Opaque
data:
  postgres_user: {{ default "postgres" .Values.env.postgres_user | b64enc | quote }}
  postgres_password: {{ default "postgres" .Values.env.postgres_password | b64enc | quote }}

{{- end }}
