#############################
####  CREATE FROST API   ####
#############################

- name: Create Frost API Entry
  uri:
    method: POST
    url: "https://apim.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/apis/import"
    return_content: yes
    body_format: json
    body: |
      {
        "proxy": {
          "endpoints": [
            {
              "name":"default",
              "target":"http://{{ frost.frost_http_serviceHost }}.svc.cluster.local:{{ frost.frost_http_ports_http_servicePort }}",
              "inherit":true
            }
          ],
          "context_path":"{{ gravitee.gateway_endpoint }}{{ gravitee.FROST_API_PATH }}"
        },
        "pages":[],
        "plans":[],
        "tags":[],
        "name":"Frost Sensorthings",
        "version":"1.0",
        "description":"Frost Server Sensorthings API"
      }
    headers:
      Accept: application/json
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 200,400
  register: frostAPI

- name: Print Frost API already exists
  debug:
    msg: "Failed. FROST API already existing?"
  when: frostAPI.status == 400

- name: Update to final Values
  uri:
    method: PUT
    url: "https://apim.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/apis/{{ frostAPI.json.id }}"
    return_content: yes
    body_format: json
    body: "{{ lookup('template', 'templates/gravitee/apis/frost/frost_sensorthings.json.j2') }}"
    headers:
      Accept: application/json
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 200
  when: frostAPI.status != 400

- name: Create Subscription Plan based on keycloak-auth
  uri:
    method: POST
    url: "https://apim.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/apis/{{ frostAPI.json.id }}/plans"
    return_content: yes
    body_format: json
    body: "{{ lookup('template', 'templates/gravitee/apis/frost/create_plan_oauth_keycloak.json.j2') }}"
    headers:
      Accept: application/json
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 201
  register: frostPlan
  when: frostAPI.status != 400

- name: Start the API
  uri:
    method: POST
    url: "https://apim.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/apis/{{ frostAPI.json.id }}?action=START"
    return_content: yes
    headers:
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 204
  when: frostAPI.status != 400

- name: Subscribe platform application to FROST API
  uri:
    method: POST
    url: "https://apim.{{ DOMAIN }}/management/organizations/DEFAULT/environments/DEFAULT/apis/{{ frostAPI.json.id }}/subscriptions?application={{ portal_app_id }}&plan={{ frostPlan.json.id }}"
    return_content: yes
    headers:
      Accept: application/json
      Authorization: Bearer {{ new_token.json.token }}
    status_code: 201,400
  register: portal_frost_subscription
  when: frostAPI.status != 400

- name: Check if already existing.
  debug:
    msg: "Failed. Subscription may already exist."
  when: frostAPI.status != 400 and portal_frost_subscription.status == 400

- name: Print subscription response
  debug:
    var: portal_orion_subscription
